run:
  concurrency: 4
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  go: '1.23'

linters:
  enable:
    - gosec
    - gci

issues:
  exclude-rules:

    - path: pkg/shsh/listen.go
      linters:
        - gosec
      text: "G114:"

    - path: pkg/spam/builder.go
      linters:
        - gosec
      text: "G404:"
