version: "2"

run:
  concurrency: 4
  tests: true
  allow-parallel-runners: true
  go: '1.24'

linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:

      - linters:
          - gosec
        path: cmd/nfguard/main.go
        text: 'G115: integer overflow conversion uint64 -> int64'

      - linters:
          - gosec
        path: cmd/nfguard/test.go
        text: 'G115: integer overflow conversion uint64 -> int64'

      - linters:
          - gosec
        path: pkg/spam/builder.go
        text: 'G404: Use of weak random number generator'

      - linters:
          - gosec
        path: pkg/spam/spam.go
        text: 'G404: Use of weak random number generator'

      - linters:
          - gosec
        path: pkg/http/proxy.go
        text: 'G404: Use of weak random number generator'

      - linters:
          - gosec
        path: pkg/http/proxy.go
        text: 'G402: TLS InsecureSkipVerify set true'

    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
