---

- name: Roles shared by every host
  hosts: all
  vars_files:
    - vars.yaml
  remote_user: "{{ ssh_user }}"
  roles:
    - base

- name: Firewall role
  hosts: baremetal
  vars_files:
    - vars.yaml
  remote_user: "{{ ssh_user }}"
  roles:
    - firewall