---

- name: Reload .network and .netdev files
  ansible.builtin.command:
    cmd: /usr/bin/networkctl reload
  listen: Networkctl reload
  changed_when: false

- name: Restart nftables
  ansible.builtin.systemd:
    daemon_reload: true
    name: nftables.service
    state: restarted
  listen: Restart nftables

- name: Restart tor
  ansible.builtin.systemd:
    daemon_reload: true
    name: tor@default.service
    state: restarted
  listen: Restart tor

- name: Restart snowflake
  ansible.builtin.systemd:
    daemon_reload: true
    name: snowflake.service
    state: restarted
  listen: Restart snowflake

- name: Restart nfguard
  ansible.builtin.systemd:
    daemon_reload: true
    name: nfguard.service
    state: restarted
  listen: Restart nfguard
