---

- name: Daemon reload
  shell: systemctl daemon-reload
  listen: daemon-reload

- name: Reload .network and .netdev files
  shell: networkctl reload
  listen: networkctl reload

- name: Restart nftables
  shell: systemctl restart nftables
  listen: restart nftables

- name: Restart sntpd
  shell: systemctl restart sntpd
  listen: restart sntpd

- name: Restart shshd
  shell: systemctl restart shshd
  listen: restart shshd

- name: Restart snid
  shell: systemctl restart snid
  listen: restart snid

- name: Restart tor
  shell: systemctl restart tor@default
  listen: restart tor

- name: Restart snowflake
  shell: systemctl restart snowflake
  listen: restart snowflake