---

- name: Daemon reload
  shell: systemctl daemon-reload
  listen: daemon-reload

- name: Reload .network and .netdev files
  shell: networkctl reload
  listen: networkctl reload

- name: Restart nftables
  shell: systemctl restart nftables
  listen: restart nftables

- name: Restart tor
  shell: systemctl restart tor@default
  listen: restart tor

- name: Restart snowflake
  shell: systemctl restart snowflake
  listen: restart snowflake

- name: Restart dnsd
  shell: systemctl restart dnsd
  listen: restart dnsd

- name: Restart nfguard
  shell: systemctl restart nfguard
  listen: restart nfguard