---

- name: Install snowflake
  copy:
    src: snowflake
    dest: "{{ snowflake_path }}"
    owner: root
    group: proxy
    mode: 0750
  notify: restart snowflake
  tags: snowflake

- name: Install the snowflake service
  template:
    src: snowflake.service.j2
    dest: /etc/systemd/system/snowflake.service
    owner: root
    group: root
    mode: 0644
  notify: daemon-reload
  tags: snowflake

- name: Enable and start snowflake
  systemd:
    name: snowflake.service
    state: started
    enabled: yes
    masked: no
  tags: snowflake