---

- name: Restart postgresql
  ansible.builtin.systemd:
    daemon_reload: true
    name: "postgresql@{{ postgresql_version }}-main.service"
    state: restarted
  listen: Restart postgresql

- name: Restart magneticod
  ansible.builtin.systemd:
    daemon_reload: true
    name: magneticod.service
    state: restarted
  listen: Restart magneticod

- name: Restart magneticow
  ansible.builtin.systemd:
    daemon_reload: true
    name: magneticow.service
    state: restarted
  listen: Restart magneticow

- name: Restart grafana
  ansible.builtin.systemd:
    daemon_reload: true
    name: grafana.service
    state: restarted
  listen: Restart grafana

- name: Restart prometheus
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus.service
    state: restarted
  listen: Restart prometheus

- name: Restart postgres-exporter
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus-postgres-exporter.service
    state: restarted
  listen: Restart postgres-exporter
