---

- name: Install dnsd
  ansible.builtin.copy:
    src: dnsd
    dest: "{{ dnsd_path }}"
    owner: nobody
    group: nogroup
    mode: '0500'
  notify: Restart dnsd
  tags: dnsd

- name: Install the dnsd service
  ansible.builtin.template:
    src: dnsd.service.j2
    dest: "{{ systemd_system }}/dnsd.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart dnsd
  tags: dnsd

- name: Enable and start dnsd
  ansible.builtin.systemd:
    name: dnsd.service
    state: started
    enabled: true
    masked: false
  tags: dnsd
