---

- name: Install nftables
  ansible.builtin.apt:
    name: nftables
    state: present
  tags: firewall

- name: Setup nftables.conf
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'
    validate: nft -c -f %s
  notify: Restart nftables
  tags: firewall

- name: Enable nftables
  ansible.builtin.systemd:
    name: nftables.service
    state: started
    enabled: true
    masked: false
  tags: firewall
