---

- name: Install nftables
  apt:
    name: nftables
    state: present
  tags: firewall

- name: Setup nftables.conf
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nftables
  tags: firewall

- name: Check nftables.conf
  shell: nft -c -f /etc/nftables.conf
  tags: firewall

- name: Enable nftables
  systemd:
    name: nftables.service
    state: started
    enabled: yes
    masked: no
  tags: firewall