---

- name: Initialize wireguard
  import_tasks: wireguard.yml

- name: Install tor
  import_tasks: tor.yml

- name: Install haproxy
  import_tasks: haproxy.yml

- name: Initialize the firewall
  import_tasks: firewall.yml

- name: Install sntpd
  import_tasks: sntpd.yml

- name: Install shshd
  import_tasks: shshd.yml

- name: Install snid
  import_tasks: snid.yml

- name: Install snowflake
  import_tasks: snowflake.yml

- name: Install dnsd
  import_tasks: dnsd.yml