---

- name: Initialize wireguard
  ansible.builtin.import_tasks: wireguard.yml

- name: Install tor
  ansible.builtin.import_tasks: tor.yml

- name: Initialize the firewall
  ansible.builtin.import_tasks: firewall.yml

- name: Install dnsd
  ansible.builtin.import_tasks: dnsd.yml

- name: Install nfguard
  ansible.builtin.import_tasks: nfguard.yml

- name: Install snowflake
  ansible.builtin.import_tasks: snowflake.yml
