---

- name: Initialize wireguard
  import_tasks: wireguard.yml

- name: Initialize the firewall
  import_tasks: firewall.yml

- name: Install sntpd
  import_tasks: sntpd.yml

- name: Install shshd
  import_tasks: shshd.yml

- name: Install snid
  import_tasks: snid.yml

- name: Install snowflake
  import_tasks: snowflake.yml