---

- name: Install nfguard
  ansible.builtin.copy:
    src: nfguard
    dest: "{{ nfguard_path }}"
    owner: proxy
    group: proxy
    mode: '0500'
  notify: restart nfguard
  tags: nfguard

- name: Install the nfguard service
  ansible.builtin.template:
    src: nfguard.service.j2
    dest: "{{ systemd_system }}/nfguard.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nfguard
  tags: nfguard

- name: Enable and start nfguard
  ansible.builtin.systemd:
    name: nfguard.service
    state: started
    enabled: true
    masked: false
  tags: nfguard
