---

- name: Install the geoip database
  apt:
    name: tor-geoipdb
    state: present
  tags: snid

- name: Install snid
  copy:
    src: snid
    dest: "{{ snid_path }}"
    owner: proxy
    group: proxy
    mode: 0500
  notify: restart snid
  tags: snid

- name: Install the snid service
  template:
    src: snid.service.j2
    dest: "{{ systemd_system }}/snid.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart snid
  tags: snid

- name: Enable and start snid
  systemd:
    name: snid.service
    state: started
    enabled: yes
    masked: no
  tags: snid