---

- name: Install snowflake
  ansible.builtin.copy:
    src: snowflake
    dest: "{{ snowflake_path }}"
    owner: root
    group: proxy
    mode: '0750'
  notify: Restart snowflake
  tags: snowflake

- name: Install the snowflake service
  ansible.builtin.template:
    src: snowflake.service.j2
    dest: "{{ systemd_system }}/snowflake.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart snowflake
  tags: snowflake

- name: Enable and start snowflake
  ansible.builtin.systemd:
    name: snowflake.service
    state: started
    enabled: true
    masked: false
  tags: snowflake
