---

- name: Install spamd
  ansible.builtin.copy:
    src: spamd
    dest: "{{ spamd_path }}"
    owner: proxy
    group: proxy
    mode: '0500'
  notify: Restart spamd
  tags: spamd

- name: Install the spamd service
  ansible.builtin.template:
    src: spamd.service.j2
    dest: "{{ systemd_system }}/spamd.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart spamd
  tags: spamd

- name: Enable and start spamd
  ansible.builtin.systemd:
    name: spamd.service
    state: started
    enabled: true
    masked: false
  tags: spamd
