---

- name: Remove hostapd
  apt:
    name: hostapd
    state: absent
  tags: wifi

- name: Remove hostapd.conf
  file:
    path: /etc/hostapd/hostapd.conf
    state: absent
  tags: wifi

- name: Remove the network profile
  file:
    path: /etc/systemd/network/wifi.network
    state: absent
  tags: wifi