---

- name: Check systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: started
    enabled: true
    masked: false
  tags: wireguard

- name: Install the network device
  ansible.builtin.template:
    src: wg0.netdev.j2
    dest: "{{ systemd_network }}/wg0.netdev"
    owner: root
    group: systemd-network
    mode: '0640'
  notify: networkctl reload
  tags: wireguard

- name: Install the network profile
  ansible.builtin.template:
    src: wg0.network.j2
    dest: "{{ systemd_network }}/wg0.network"
    owner: root
    group: root
    mode: '0644'
  notify: networkctl reload
  tags: wireguard
