---

- name: Check if folder exist for grafana
  ansible.builtin.stat:
    path: "{{ grafana_folder }}"
  register: grafana_installed
  tags: grafana

- name: Extract the standalone archive
  ansible.builtin.unarchive:
    src: "grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    dest: "{{ local_folder }}"
    remote_src: false
  when: not grafana_installed.stat.exists
  tags: grafana

- name: Setup grafana
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: "{{ grafana_folder }}/conf/grafana.ini"
    owner: root
    group: root
    mode: '0644'
  notify: Restart grafana
  tags: grafana

- name: Set the magnetico service facts
  ansible.builtin.set_fact:
    service_after: "postgresql.service"
    service_ambient_capabilities: ""
    service_capability_bounding_set: ""
    service_description: "Grafana instance"
    service_exec_start: "{{ grafana_folder }}/bin/grafana server --config={{ grafana_folder }}/conf/grafana.ini"
    service_group: "nogroup"
    service_limit_nofile: 32768
    service_protect_clock: "yes"
    service_restrict_address_families: "AF_INET AF_INET6"
    service_umask: "0027"
    service_user: "nobody"
    service_working_directory: "{{ grafana_folder }}"
  tags: grafana

- name: Setup the grafana systemd service
  ansible.builtin.template:
    src: sandboxed.service.j2
    dest: "{{ systemd_system }}/grafana.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart grafana
  tags: grafana

- name: Enable and start grafana
  ansible.builtin.systemd:
    name: grafana.service
    state: started
    enabled: true
    masked: false
  tags: grafana
