---

- name: Install magnetico
  ansible.builtin.copy:
    src: magnetico
    dest: "{{ master_magnetico_path }}"
    owner: proxy
    group: proxy
    mode: '0500'
  notify: Restart magnetico
  tags: magnetico

- name: Set the magnetico service facts
  ansible.builtin.set_fact:
    service_after: "postgresql.service"
    service_ambient_capabilities: ""
    service_capability_bounding_set: ""
    service_description: "Magnetico Daemon"
    service_exec_start: "{{ master_magnetico_path }} --max-rps={{ master_magneticod_maxrps }} --pyroscope=http://127.0.0.1:4040 --addr=[{{ master_wg0_ipv6 }}]:8080 --indexer-addr=:25401"
    service_group: "proxy"
    service_limit_nofile: 32768
    service_protect_clock: "yes"
    service_readwrite_paths: ""
    service_restrict_address_families: "AF_INET AF_INET6"
    service_umask: "777"
    service_user: "proxy"
    service_working_directory: ""
  tags: magnetico

- name: Install the magnetico service
  ansible.builtin.template:
    src: sandboxed.service.j2
    dest: "{{ systemd_system }}/magnetico.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart magnetico
  tags: magnetico

- name: Enable and start magnetico
  ansible.builtin.systemd:
    name: magnetico.service
    state: started
    enabled: true
    masked: false
  tags: magnetico
