---

- name: Initialize wireguard
  ansible.builtin.import_tasks: wireguard.yml

- name: Install tor
  ansible.builtin.import_tasks: tor.yml

- name: Install postgresql
  ansible.builtin.import_tasks: postgresql.yml

- name: Install transmission
  ansible.builtin.import_tasks: transmission.yml

- name: Initialize the firewall
  ansible.builtin.import_tasks: firewall.yml

- name: Install nfguard
  ansible.builtin.import_tasks: nfguard.yml

- name: Install snowflake
  ansible.builtin.import_tasks: snowflake.yml

- name: Install magnetico
  ansible.builtin.import_tasks: magnetico.yml

- name: Install grafana
  ansible.builtin.import_tasks: grafana.yml

- name: Install prometheus
  ansible.builtin.import_tasks: prometheus.yml

- name: Install pyroscope
  ansible.builtin.import_tasks: pyroscope.yml
