---

- name: Install nfguard
  ansible.builtin.copy:
    src: nfguard
    dest: "{{ master_nfguard_path }}"
    owner: www-data
    group: www-data
    mode: '0500'
  notify: Restart nfguard
  tags: nfguard

- name: Set the nfguard service facts
  ansible.builtin.set_fact:
    master_service_after: "postgresql.service"
    master_service_ambient_capabilities: "CAP_NET_BIND_SERVICE"
    master_service_capability_bounding_set: "CAP_NET_BIND_SERVICE"
    master_service_description: "NetFilter Tables Guard Daemon"
    master_service_exec_start: "{{ master_nfguard_path }} -interfaceIPv4 {{ master_wg0_ipv4 }} -interfaceIPv6 [{{ master_wg0_ipv6 }}]"
    master_service_group: "www-data"
    master_service_limit_nofile: "infinity"
    master_service_memory_deny_write_execute: "true"
    master_service_protect_clock: "false"
    master_service_readwrite_paths: "/var/www"
    master_service_restrict_address_families: "AF_INET AF_INET6"
    master_service_umask: "177"
    master_service_user: "www-data"
    master_service_working_directory: ""
  tags: nfguard

- name: Install the nfguard service
  ansible.builtin.template:
    src: sandboxed.service.j2
    dest: "{{ systemd_system }}/nfguard.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart nfguard
  tags: nfguard

- name: Enable and start nfguard
  ansible.builtin.systemd:
    name: nfguard.service
    state: started
    enabled: true
    masked: false
  tags: nfguard
