---

- name: Install nfguard
  ansible.builtin.copy:
    src: nfguard
    dest: "{{ nfguard_path }}"
    owner: www-data
    group: www-data
    mode: '0500'
  notify: Restart nfguard
  tags: nfguard

- name: Set the nfguard service facts
  ansible.builtin.set_fact:
    service_after: "postgresql.service"
    service_ambient_capabilities: "CAP_NET_BIND_SERVICE"
    service_capability_bounding_set: "CAP_NET_BIND_SERVICE"
    service_description: "NetFilter Tables Guard Daemon"
    service_exec_start: "{{ nfguard_path }} -interfaceIPv4 {{ wg0_ipv4 }} -interfaceIPv6 [{{ wg0_ipv6 }}]"
    service_group: "www-data"
    service_limit_nofile: "infinity"
    service_protect_clock: "no"
    service_readwrite_paths: "/var/www"
    service_restrict_address_families: "AF_INET AF_INET6"
    service_umask: "177"
    service_user: "www-data"
    service_working_directory: ""
  tags: nfguard

- name: Install the nfguard service
  ansible.builtin.template:
    src: sandboxed.service.j2
    dest: "{{ systemd_system }}/nfguard.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart nfguard
  tags: nfguard

- name: Enable and start nfguard
  ansible.builtin.systemd:
    name: nfguard.service
    state: started
    enabled: true
    masked: false
  tags: nfguard
