---

- name: Ensure the pyroscope group exists
  ansible.builtin.group:
    name: pyroscope
    system: true
    state: present
  tags: pyroscope

- name: Ensure the pyroscope user exists
  ansible.builtin.user:
    name: pyroscope
    group: pyroscope
    system: true
    shell: /bin/false
    home: "{{ master_pyroscope_datapath }}"
    state: present
  tags: pyroscope

- name: Check if folder exist for pyroscope
  ansible.builtin.stat:
    path: "{{ master_pyroscope_folder }}"
  register: master_pyroscope_installed
  tags: pyroscope

- name: Ensure the pyroscope app directory exists
  ansible.builtin.file:
    path: "{{ master_pyroscope_folder }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: pyroscope

- name: Extract the standalone archive
  ansible.builtin.unarchive:
    src: "pyroscope_{{ master_pyroscope_version }}_linux_amd64.tar.gz"
    dest: "{{ master_pyroscope_folder }}"
    remote_src: false
  when: not master_pyroscope_installed.stat.exists
  tags: pyroscope

- name: Setup pyroscope
  ansible.builtin.template:
    src: pyroscope.yml.j2
    dest: "{{ master_pyroscope_folder }}/pyroscope.yml"
    owner: root
    group: root
    mode: '0644'
  tags: pyroscope

- name: Set the pyroscope service facts
  ansible.builtin.set_fact:
    master_service_after: ""
    master_service_ambient_capabilities: ""
    master_service_capability_bounding_set: ""
    master_service_description: "Pyroscope instance"
    master_service_exec_start: "{{ master_pyroscope_folder }}/pyroscope --config.file={{ master_pyroscope_folder }}/pyroscope.yml"
    master_service_group: "pyroscope"
    master_service_limit_nofile: 32768
    master_service_memory_deny_write_execute: "true"
    master_service_protect_clock: "true"
    master_service_readwrite_paths: "{{ master_pyroscope_datapath }}"
    master_service_restrict_address_families: "AF_INET AF_INET6 AF_NETLINK"
    master_service_umask: "0027"
    master_service_user: "pyroscope"
    master_service_working_directory: "{{ master_pyroscope_datapath }}"
  tags: pyroscope

- name: Setup the pyroscope systemd service
  ansible.builtin.template:
    src: sandboxed.service.j2
    dest: "{{ systemd_system }}/pyroscope.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart pyroscope
  tags: pyroscope

- name: Enable and start pyroscope
  ansible.builtin.systemd:
    name: pyroscope.service
    state: started
    enabled: true
    masked: false
  tags: pyroscope
