---

- name: Install snowflake
  ansible.builtin.copy:
    src: snowflake
    dest: "{{ snowflake_path }}"
    owner: root
    group: proxy
    mode: '0750'
  notify: Restart snowflake
  tags: snowflake

- name: Set the snowflake service facts
  ansible.builtin.set_fact:
    service_ambient_capabilities: ""
    service_capability_bounding_set: ""
    service_description: "Snowflake Proxy Daemon"
    service_exec_start: "{{ snowflake_path }} -unsafe-logging -nat-type-force-unrestricted -ephemeral-ports-range 1024:65535 -metrics"
    service_group: "proxy"
    service_limit_nofile: 32768
    service_protect_clock: "yes"
    service_restrict_address_families: "AF_INET AF_INET6"
    service_user: "proxy"
  tags: snowflake

- name: Install the snowflake service
  ansible.builtin.template:
    src: sandboxed.service.j2
    dest: "{{ systemd_system }}/snowflake.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart snowflake
  tags: snowflake

- name: Enable and start snowflake
  ansible.builtin.systemd:
    name: snowflake.service
    state: started
    enabled: true
    masked: false
  tags: snowflake
