---

- name: Load tor defaults
  ansible.builtin.include_vars: "{{ role_path }}/defaults/tor.yml"
  tags: tor

- name: Install tor
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - tor
    - tor-geoipdb
  tags: tor

- name: Install the snowflake client
  ansible.builtin.copy:
    src: client
    dest: "{{ master_client_path }}"
    owner: debian-tor
    group: debian-tor
    mode: '0750'
  notify: Restart tor
  tags: tor

- name: Setup torrc
  ansible.builtin.template:
    src: torrc.j2
    dest: /etc/tor/torrc
    owner: root
    group: root
    mode: '0644'
    validate: tor --verify-config -f %s
  notify: Restart tor
  tags: tor

- name: Install the tor service
  ansible.builtin.template:
    src: tor.service.j2
    dest: "{{ systemd_system }}/tor@default.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart tor
  tags: tor

- name: Enable and start tor
  ansible.builtin.systemd:
    name: tor@default.service
    state: started
    enabled: true
    masked: false
  tags: tor
