---

- name: Install systemd-resolved
  apt:
    name: systemd-resolved
    state: present
  tags: dns

- name: Setup systemd-resolved
  template:
    src: resolved.conf.j2
    dest: "{{ systemd_prefix }}/resolved.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart resolved
  tags: dns

- name: Enable systemd-resolved
  systemd:
    name: systemd-resolved.service
    state: started
    enabled: yes
    masked: no
  tags: dns

- name: Setup resolv.conf
  file:
    src: /var/run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
  tags: dns