---

- name: Prepare for the symlink phase
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - /media/cdrom
    - /media/cdrom0
    - /var/spool/cron
    - /var/spool/mail
  tags: fhs

- name: Symlink to /dev/null
  ansible.builtin.file:
    force: true
    src: /dev/null
    dest: "{{ item }}"
    state: link
  loop:
    - /home
    - /media
    - /mnt
    - /opt
    - /srv
    - /var/cache/private
    - /var/lib/private
    - /var/local
    - /var/mail
    - /var/opt
    - /var/spool
  tags: fhs

- name: Cleanup /etc
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - /etc/dhcp
    - /etc/logrotate.d
    - /etc/opt
    - /etc/rc0.d
    - /etc/rc1.d
    - /etc/rc2.d
    - /etc/rc3.d
    - /etc/rc4.d
    - /etc/rc5.d
    - /etc/rc6.d
    - /etc/rcS.d
    - /etc/runit
    - /etc/sv
    - /etc/ufw
  tags: fhs
