---

- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  tags: init

- name: Set apt sources
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  tags: init

- name: Delete old apt sources
  file:
    state: absent
    path: "{{item}}"
  with_items:
    - /etc/apt/sources.list.d
    - /etc/apt/sources.list~
  tags: init

- name: Configure apt
  copy:
    src: 99custom
    dest: /etc/apt/apt.conf.d/99custom
    owner: root
    group: root
    mode: 0644
  tags: init

- name: Update the apt cache
  apt:
    update_cache: yes
  tags: init

- name: Install essential packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - aptitude
    - hardening-runtime
    - htop
    - iproute2
    - locales-all
    - lsof
    - tmux
  tags: init

- name: Remove default packages
  apt:
    name: "{{item}}"
    state: absent
  with_items:
    - cron
    - cron-daemon-common
    - dmidecode
    - ifupdown
    - laptop-detect
    - locales
    - logrotate
    - tasksel
    - tasksel-data
  tags: init

- name: Disable futile services
  systemd:
    name: "{{item}}"
    state: stopped
    enabled: no
    masked: yes
  with_items:
    - emergency.service
    - rc-local.service
    - rescue.service
    - systemd-ask-password-console.path
    - systemd-ask-password-console.service
    - systemd-ask-password-wall.path
    - systemd-ask-password-wall.service
    - systemd-initctl.service
    - systemd-initctl.socket
    - systemd-rfkill.service
    - systemd-rfkill.socket
    - user@0.service
  tags: init