---

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  tags: init

- name: Set apt sources
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  tags: init

- name: Delete old apt sources
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - /etc/apt/sources.list.d
    - /etc/apt/sources.list~
  tags: init

- name: Configure apt
  template:
    src: 99custom.j2
    dest: /etc/apt/apt.conf.d/99custom
    owner: root
    group: root
    mode: 0644
  tags: init

- name: Update the apt cache
  apt:
    update_cache: yes
  tags: init

- name: Install essential packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - aptitude
    - btrfs-progs
    - gdisk 
    - hardening-runtime
    - htop
    - iproute2
    - lm-sensors
    - locales-all
    - lsof
    - man-db
    - manpages
    - manpages-it
    - smartmontools
    - tcpdump
    - tmux
  tags: init

- name: Customize the hardening runtime
  lineinfile:
    path: /etc/default/grub.d/01_hardening.cfg
    line: GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT intel_iommu=on"
    state: present
  notify: update grub
  tags: init

- name: Remove default packages
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - cron
    - cron-daemon-common
    - dmidecode
    - ifupdown
    - laptop-detect
    - locales
    - logrotate
    - tasksel
    - tasksel-data
  tags: init

- name: Disable futile services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
  loop:
    - emergency.service
    - rc-local.service
    - rescue.service
    - systemd-ask-password-console.path
    - systemd-ask-password-console.service
    - systemd-ask-password-wall.path
    - systemd-ask-password-wall.service
    - systemd-initctl.service
    - systemd-initctl.socket
    - systemd-rfkill.service
    - systemd-rfkill.socket
    - user@0.service
  tags: init