---

- name: Bootstrap apt tor transport
  ansible.builtin.apt:
    name: "apt-transport-tor"
    state: present
  tags: init

- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  tags: init

- name: Set apt sources
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
  tags: init

- name: Delete old apt sources
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - /etc/apt/sources.list.d
    - /etc/apt/sources.list~
  tags: init

- name: Configure apt
  ansible.builtin.template:
    src: 99custom.j2
    dest: /etc/apt/apt.conf.d/99custom
    owner: root
    group: root
    mode: '0644'
  tags: init

- name: Update the apt cache
  ansible.builtin.apt:
    update_cache: true
  tags: init

- name: Install essential packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - aptitude
    - btrfs-progs
    - gdisk
    - hardening-runtime
    - htop
    - iproute2
    - lm-sensors
    - locales-all
    - lsof
    - man-db
    - manpages
    - manpages-dev
    - manpages-it
    - nano
    - smartmontools
    - tcpdump
    - tmux
  tags: init

- name: Customize the hardening runtime
  ansible.builtin.lineinfile:
    path: /etc/default/grub.d/01_hardening.cfg
    line: GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT intel_iommu=on"
    state: present
  notify: Update grub
  tags: init

- name: Remove default packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - cron
    - cron-daemon-common
    - dmidecode
    - ifupdown
    - laptop-detect
    - locales
    - logrotate
    - tasksel
    - tasksel-data
  tags: init

- name: Disable futile services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  loop:
    - emergency.service
    - rc-local.service
    - rescue.service
    - systemd-ask-password-console.path
    - systemd-ask-password-console.service
    - systemd-ask-password-wall.path
    - systemd-ask-password-wall.service
    - systemd-initctl.service
    - systemd-initctl.socket
    - systemd-rfkill.service
    - systemd-rfkill.socket
    - user@0.service
  tags: init

- name: Remove default system users
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
  loop:
    - bin
    - caddy
    - daemon
    - debian
    - irc
    - list
    - loki
    - lp
    - mail
    - news
    - systemd-resolve
    - uucp
  tags: init
