---

- name: Check systemd-networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: yes
    masked: no
  tags: network

- name: Install network profiles
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/network/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - enp.network
    - wan.netdev
    - wan.network
  notify: networkctl reload
  tags: network

- name: Delete unused directories
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/network
    - /etc/sysctl.d
  tags: network

- name: Remove comments from /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#' 
    state: absent
  tags: network

- name: Remove empty lines from /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^\s*$'
    state: absent
  tags: network

- name: Setting sysctl.conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - name: kernel.printk
      value: 3 4 1 3
    - name: net.ipv4.conf.default.rp_filter
      value: 1
    - name: net.ipv4.conf.all.rp_filter
      value: 1
    - name: net.ipv4.tcp_syncookies
      value: 1
    - name: net.ipv4.tcp_rfc1337
      value: 1
    - name: net.ipv4.tcp_timestamps
      value: 0
    - name: net.ipv4.icmp_echo_enable_probe
      value: 0
    - name: net.ipv4.icmp_echo_ignore_all
      value: 1
    - name: net.ipv4.icmp_echo_ignore_broadcasts
      value: 1
    - name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
    - name: net.ipv4.icmp_msgs_burst
      value: 1
    - name: net.ipv4.icmp_msgs_per_sec
      value: 2
    - name: net.ipv4.icmp_ratelimit
      value: 10
    - name: net.ipv6.icmp.echo_ignore_all
      value: 1
    - name: kernel.unprivileged_bpf_disabled
      value: 1
    - name: net.ipv4.ip_forward
      value: 0
    - name: net.ipv6.conf.all.forwarding
      value: 0
    - name: net.ipv4.conf.all.accept_redirects
      value: 0
    - name: net.ipv6.conf.all.accept_redirects
      value: 0
    - name: net.ipv4.conf.all.secure_redirects
      value: 0
    - name: net.ipv4.conf.all.send_redirects
      value: 0
    - name: net.ipv4.conf.all.accept_source_route
      value: 0
    - name: net.ipv6.conf.all.accept_source_route
      value: 0
    - name: net.ipv4.conf.all.log_martians
      value: 0
    - name: net.ipv4.ip_local_port_range
      value: 1024 65535
    - name: net.core.default_qdisc
      value: fq
    - name: net.ipv4.tcp_congestion_control
      value: bbr
    - name: net.core.rmem_max
      value: 16777216
    - name: net.core.wmem_max
      value: 16777216
    - name: net.ipv4.tcp_mem
      value: 8192 262144 16777216
    - name: net.ipv4.tcp_rmem
      value: 4096 131072 16777216
    - name: net.ipv4.tcp_wmem
      value: 4096 131072 16777216
    - name: net.ipv4.udp_mem
      value: 1048576 2097152 16777216
    - name: net.ipv4.udp_rmem_min
      value: 131072
    - name: net.ipv4.udp_wmem_min
      value: 131072
    - name: net.ipv4.tcp_fastopen
      value: 3
  tags: network