---

- name: Check systemd-networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: yes
    masked: no
  tags: network

- name: Install network profiles
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/network/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - enp.network
    - wan.netdev
    - wan.network
  notify: networkctl reload
  tags: network

- name: Delete /etc/network
  file:
    state: absent
    path: /etc/network
  tags: network

- name: Delete /etc/sysctl.d
  file:
    state: absent
    path: /etc/sysctl.d
  tags: network

- name: Remove comments from /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#' 
    state: absent
  tags: network

- name: Remove empty lines from /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^\s*$'
    state: absent
  tags: network

- name: Setting kernel.printk
  sysctl:
    name: kernel.printk
    value: 3 4 1 3
  tags: network

- name: Setting net.ipv4.conf.default.rp_filter
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 1
  tags: network

- name: Setting net.ipv4.conf.all.rp_filter
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
  tags: network

- name: Setting net.ipv4.tcp_syncookies
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
  tags: network

- name: Setting net.ipv4.tcp_rfc1337
  sysctl:
    name: net.ipv4.tcp_rfc1337
    value: 1
  tags: network

- name: Setting net.ipv4.tcp_timestamps
  sysctl:
    name: net.ipv4.tcp_timestamps
    value: 0
  tags: network

- name: Setting net.ipv4.icmp_echo_enable_probe
  sysctl:
    name: net.ipv4.icmp_echo_enable_probe
    value: 0
  tags: network

- name: Setting net.ipv4.icmp_echo_ignore_all
  sysctl:
    name: net.ipv4.icmp_echo_ignore_all
    value: 1
  tags: network

- name: Setting net.ipv4.icmp_echo_ignore_broadcasts
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
  tags: network

- name: Setting net.ipv4.icmp_ignore_bogus_error_responses
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
  tags: network

- name: Setting net.ipv4.icmp_msgs_burst
  sysctl:
    name: net.ipv4.icmp_msgs_burst
    value: 1
  tags: network

- name: Setting net.ipv4.icmp_msgs_per_sec
  sysctl:
    name: net.ipv4.icmp_msgs_per_sec
    value: 2
  tags: network

- name: Setting net.ipv4.icmp_ratelimit
  sysctl:
    name: net.ipv4.icmp_ratelimit
    value: 10
  tags: network

- name: Setting net.ipv6.icmp.echo_ignore_all
  sysctl:
    name: net.ipv6.icmp.echo_ignore_all
    value: 1
  tags: network

- name: Setting kernel.unprivileged_bpf_disabled
  sysctl:
    name: kernel.unprivileged_bpf_disabled
    value: 1
  tags: network

- name: Setting net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
  tags: network

- name: Setting net.ipv6.conf.all.forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 0
  tags: network

- name: Setting net.ipv4.conf.all.accept_redirects
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: 0
  tags: network

- name: Setting net.ipv6.conf.all.accept_redirects
  sysctl:
    name: net.ipv6.conf.all.accept_redirects
    value: 0
  tags: network

- name: Setting net.ipv4.conf.all.secure_redirects
  sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: 0
  tags: network

- name: Setting net.ipv4.conf.all.send_redirects
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
  tags: network

- name: Setting net.ipv4.conf.all.accept_source_route
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: 0
  tags: network

- name: Setting net.ipv6.conf.all.accept_source_route
  sysctl:
    name: net.ipv6.conf.all.accept_source_route
    value: 0
  tags: network

- name: Setting net.ipv4.conf.all.log_martians
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 0
  tags: network

- name: Setting net.ipv4.ip_local_port_range
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: 1024 65535
  tags: network

- name: Setting net.core.default_qdisc
  sysctl:
    name: net.core.default_qdisc
    value: fq
  tags: network

- name: Setting net.ipv4.tcp_congestion_control
  sysctl:
    name: net.ipv4.tcp_congestion_control
    value: bbr
  tags: network

- name: Setting net.core.rmem_max
  sysctl:
    name: net.core.rmem_max
    value: 16777216
  tags: network

- name: Setting net.core.wmem_max
  sysctl:
    name: net.core.wmem_max
    value: 16777216
  tags: network

- name: Setting net.ipv4.tcp_mem
  sysctl:
    name: net.ipv4.tcp_mem
    value: 8192 262144 16777216
  tags: network

- name: Setting net.ipv4.tcp_rmem
  sysctl:
    name: net.ipv4.tcp_rmem
    value: 4096 131072 16777216
  tags: network

- name: Setting net.ipv4.tcp_wmem
  sysctl:
    name: net.ipv4.tcp_wmem
    value: 4096 131072 16777216
  tags: network

- name: Setting net.ipv4.udp_mem
  sysctl:
    name: net.ipv4.udp_mem
    value: 1048576 2097152 16777216
  tags: network

- name: Setting net.ipv4.udp_rmem_min
  sysctl:
    name: net.ipv4.udp_rmem_min
    value: 131072
  tags: network

- name: Setting net.ipv4.udp_wmem_min
  sysctl:
    name: net.ipv4.udp_wmem_min
    value: 131072
  tags: network