---

- name: Install magnetico
  ansible.builtin.copy:
    src: magnetico
    dest: "{{ magnetico_path }}"
    owner: daemon
    group: daemon
    mode: '0500'
  notify: Restart magnetico
  tags: magnetico

- name: Install the magnetico service
  ansible.builtin.template:
    src: magnetico.service.j2
    dest: "{{ systemd_system }}/magnetico.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart magnetico
  tags: magnetico

- name: Enable and start magnetico
  ansible.builtin.systemd:
    name: magnetico.service
    state: started
    enabled: true
    masked: false
  tags: magnetico
