---

- name: Install postgresql
  ansible.builtin.import_tasks: postgresql.yml

- name: Install magnetico
  ansible.builtin.import_tasks: magnetico.yml

- name: Install grafana
  ansible.builtin.import_tasks: grafana.yml
