---

- name: Install postgresql
  ansible.builtin.import_tasks: postgresql.yml

- name: Install magnetico
  ansible.builtin.import_tasks: magnetico.yml

- name: Install grafana
  ansible.builtin.import_tasks: grafana.yml

- name: Install prometheus
  ansible.builtin.import_tasks: prometheus.yml

- name: Install samba
  ansible.builtin.import_tasks: samba.yml
  when:
    - smb_user is defined
    - smb_paths is defined
