---

- name: Install prometheus
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - prometheus
    - prometheus-node-exporter
    - prometheus-postgres-exporter
    - prometheus-blackbox-exporter
  tags: prometheus

- name: Copy prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
  notify: Restart prometheus
  tags: prometheus

- name: Install the prometheus service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: "{{ systemd_system }}/prometheus.service"
    owner: root
    group: root
    mode: '0644'
  notify: Restart prometheus
  tags: prometheus

- name: Copy the postgres exporter configuration
  ansible.builtin.template:
    src: prometheus-postgres-exporter.j2
    dest: /etc/default/prometheus-postgres-exporter
    owner: root
    group: root
    mode: '0644'
  notify: Restart postgres-exporter
  tags: prometheus

- name: Enable and start prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started
  tags: prometheus
